name: Flutter CI/CD Workflow

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Create .env file from secrets
        run: |
          cat <<EOF > .env
          NEON_HOST=${{ secrets.NEON_HOST }}
          NEON_DATABASE=${{ secrets.NEON_DATABASE }}
          NEON_USERNAME=${{ secrets.NEON_USERNAME }}
          NEON_PASSWORD=${{ secrets.NEON_PASSWORD }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          TMDB_ACCESS_TOKEN=${{ secrets.TMDB_ACCESS_TOKEN }}
          TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}
          WYZIE_API_KEY=${{ secrets.WYZIE_API_KEY }}
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze || true

      - name: Run unit and widget tests
        run: flutter test

      - name: Build Web app
        run: flutter build web --release

      - name: Build Android APK
        run: flutter build apk --release
